import {useEffect,useState} from 'react';
import {Send,Sparkles} from 'lucide-react';
import {api,requireDb} from '../lib/db';
import type {Learner} from '../lib/useLearner';
export function Tutor({learner,login}:{learner:Learner;login:()=>void}){
 const [messages,setMessages]=useState<{role:string;content:string}[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[interestMode,setInterestMode]=useState(!learner.profile?.interest);
 useEffect(()=>{if(!learner.session)return;requireDb().from('messages').select('role,content').order('id',{ascending:false}).limit(30).then(({data,error})=>{if(error)setError('No se pudo cargar la conversación.');else setMessages((data??[]).reverse());});},[learner.session]);
 async function send(e:React.FormEvent){e.preventDefault();if(!learner.session){login();return;}setBusy(true);setError('');try{
  if(interestMode){await learner.updateProfile({interest:text.slice(0,500)});setInterestMode(false);setText('');return;}
  const result=await api<{text:string}>('ai',{operation:'tutor',message:text});setMessages(m=>[...m,{role:'user',content:text},{role:'assistant',content:result.text}]);setText('');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="tutor-layout"><div className="panel chat-panel"><div className="row"><div className="tutor-orb"><Sparkles/></div><div><h2>Tu espacio para practicar</h2><span className="muted">Tutor por texto · inglés a tu ritmo</span></div></div><div className="chat-messages" aria-live="polite">{!messages.length&&<div className="chat-welcome"><h1>¿Qué te gustaría poder hacer en inglés?</h1><p>Cuéntame tu interés principal: viajar, hablar de tecnología, crecer en tu trabajo o algo completamente distinto.</p><div className="row wrap">{['Viajar con confianza','Inglés para mi trabajo','Tecnología y videojuegos'].map(t=><button key={t} className="chip" onClick={()=>{setInterestMode(true);setText(t);}}>{t}</button>)}</div></div>}{learner.profile?.interest&&<p className="interest-note">Tu interés guardado: <strong>{learner.profile.interest}</strong> <button className="text-button" onClick={()=>setInterestMode(true)}>Cambiar</button></p>}{messages.map((m,i)=><div key={i} className={`message ${m.role}`}><small>{m.role==='user'?'Tú':'Lingora'}</small><p className="preserve">{m.content}</p></div>)}</div><form className="chat-compose" onSubmit={send}><label className="sr-only" htmlFor="chat-input">{interestMode?'Tu interés principal':'Mensaje para el tutor'}</label><textarea id="chat-input" rows={2} maxLength={interestMode?500:2000} value={text} onChange={e=>setText(e.target.value)} placeholder={interestMode?'Mi interés principal es…':'Escribe en inglés o pregunta en español…'} required/><button className="primary" aria-label={interestMode?'Guardar interés':'Enviar mensaje'} disabled={busy||!text.trim()}><Send size={19}/></button></form><small>{interestMode?'Guardaremos este interés en tu perfil para adaptar los temas.':'Las respuestas del tutor pueden contener errores. Puedes pedir una explicación o reportarlas.'}</small>{busy&&<p role="status">Un momento…</p>}{error&&<p className="error" role="alert">{error}</p>}</div><aside className="panel tutor-tips"><span className="eyebrow">PEQUEÑAS CONVERSACIONES</span><h3>Grandes pasos</h3><p>No necesitas una frase perfecta para comenzar.</p><ul><li>Pide un ejemplo de tu vida diaria.</li><li>Prueba una respuesta en inglés.</li><li>Pregunta por qué se corrige algo.</li></ul><hr/><p>El tutor usa tu nivel, interés y errores recientes. Las lecciones y los repasos funcionan independientemente de la IA.</p></aside></section>;
}
