import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {curriculum} from '../src/data/curriculum';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth;
 create table auth.users(id uuid primary key,email text);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema public,auth to anon,authenticated,service_role; grant execute on function auth.uid() to anon,authenticated,service_role;`);
await db.exec(await readFile('supabase/migrations/001_initial.sql','utf8'));
const one='11111111-1111-4111-8111-111111111111',two='22222222-2222-4222-8222-222222222222';
await db.exec(`insert into pilot_invites values('one@example.test'),('two@example.test');insert into auth.users values('${one}','one@example.test'),('${two}','two@example.test');`);
for(const l of curriculum)await db.query('insert into lessons(id,level,skill,payload) values($1,$2,$3,$4)',[l.id,l.level,l.skill,JSON.stringify(l)]);
async function asUser<T>(id:string,fn:()=>Promise<T>){await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${id}',false)`);try{return await fn();}finally{await db.exec('reset role');}}
await asUser(one,async()=>{
 const p=await db.query('select * from profiles');assert.equal(p.rows.length,1);
 await assert.rejects(()=>db.exec(`insert into lesson_progress(user_id,lesson_id) values('${one}','a1-vocabulary')`));
 await db.query('select submit_exercise($1,$2,$3)',['a1-vocabulary',0,'nombre']);
 await assert.rejects(()=>db.query('select submit_exercise($1,$2,$3)',['a1-vocabulary',0,'nombre']),/CONFLICT/);
 await db.query('select submit_exercise($1,$2,$3)',['a1-vocabulary',1,'wrong']);
 await db.query('select submit_exercise($1,$2,$3)',['a1-vocabulary',2,'vivir']);
 await db.query('select submit_exercise($1,$2,$3)',['a1-vocabulary',3,'amigo o amiga']);
 const progress=await db.query<{completed:boolean;correct:number;attempts:number}>('select * from lesson_progress');assert.equal(progress.rows[0].completed,true);assert.equal(progress.rows[0].correct,3);assert.equal(progress.rows[0].attempts,4);
 assert.equal((await db.query('select * from user_errors')).rows.length,1);
 const reviews=await db.query<{id:string}>('select * from reviews');assert.equal(reviews.rows.length,5);
 await db.query('select rate_review($1,0,4)',[reviews.rows[0].id]);
 await assert.rejects(()=>db.query('select rate_review($1,0,4)',[reviews.rows[0].id]),/CONFLICT/);
 await assert.rejects(()=>db.query('select reserve_ai($1,$2,5,10,2)',[one,'tutor']),/permission denied/);
 await db.query('select save_diagnostic(0,true)');
 await db.query("select save_diagnostic(1,false,'a2-vocabulary','boleto')");
 await assert.rejects(()=>db.query('select save_diagnostic(1,true)'),/CONFLICT/);
});
await asUser(two,async()=>{assert.equal((await db.query('select * from lesson_progress')).rows.length,0);assert.equal((await db.query('select * from diagnostics')).rows.length,0);assert.equal((await db.query('select * from reviews')).rows.length,0);await db.exec(`update profiles set interest='hacked' where id='${one}'`);});
assert.equal((await db.query<{interest:string}>('select interest from profiles where id=$1',[one])).rows[0].interest,'');
await db.exec(`update diagnostics set elapsed_seconds=899,active=true,updated_at=now()-interval '10 seconds' where user_id='${one}'`);
await asUser(one,async()=>{await db.query('select save_diagnostic(2,true)');const d=await db.query<{completed:boolean;elapsed_seconds:number}>('select * from diagnostics');assert.equal(d.rows[0].completed,true);assert.equal(d.rows[0].elapsed_seconds,900);});
await db.query('select reserve_ai($1,$2,1,2,1)',[one,'tutor']);
await assert.rejects(()=>db.query('select reserve_ai($1,$2,1,2,1)',[one,'tutor']),/AI_QUOTA/);
await db.exec(`delete from auth.users where id='${one}'`);assert.equal((await db.query('select * from lesson_progress')).rows.length,0);
console.log('PASS: migration, invite-only signup, RLS isolation, deterministic grading, idempotency, SRS, diagnostic conflicts/time cap, AI quota and account cascade.');
await db.close();
